version: '3.8'

services: 
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes: 
      - db_data:/var/lib/mysql
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: node-mysql
  #   ports: 
  #     - 5000:5000
  #   depends_on:
  #     - mysql
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./:/home/node/app
  #   command: bash -c " npm install && npm run dev"
volumes: 
  db_data: